"""PHASE 1: Memory Metadata System

Metadata fields added in Phase 1 to prevent architectural dead-ends:

1. generated_by: Who created this entry? "user" | "zypherus" | "system"
   - Prevents recursive contamination
   - Enables self-output quarantine

2. certainty: How confident is this information? 0.0-1.0
   - Marks speculation vs verified facts
   - Prevents treating guesses as facts
   - Weighted in retrieval scoring

3. is_assumption: Is this an assumption? Boolean
   - Marks assumed vs verified premises
   - Enables "if assumption X is wrong, then..."
   - Tracks dependency chains

These fields are automatically populated during ingestion and weighted during retrieval.
"""

import re
from typing import Tuple


class Phase1Metadata:
	"""Utilities for Phase 1 metadata: generated_by, certainty, is_assumption."""
	
	# Patterns that indicate speculation/assumptions
	SPECULATION_PATTERNS = [
		r"(?:might|may|could|perhaps|possibly|probably|likely)",
		r"(?:seems|appears|suggests|indicates)",
		r"(?:i think|i believe|in my opinion|arguably|debatable)",
		r"(?:suggests that|implies that|would mean|would indicate)",
		r"(?:unknown|unclear|uncertain|debatable)",
		r"(?:presumably|allegedly|reportedly)",
	]
	
	# Patterns that indicate assumptions (premises accepted without proof)
	ASSUMPTION_PATTERNS = [
		r"assuming",
		r"given that",
		r"if we assume",
		r"hypothetical",
		r"imagine(?:d|s)?",
		r"suppose(?:d)?",
		r"let'?s say",
		r"in theory",
		r"theoretically",
		r"for the sake of argument",
		r"by definition",  # Often assumes shared understanding
	]
	
	# Patterns that indicate high certainty
	HIGH_CERTAINTY_PATTERNS = [
		r"always",
		r"never",
		r"definitely",
		r"certainly",
		r"scientifically",
		r"proven",
		r"verified",
		r"confirmed",
		r"established",
		r"universal law",
	]
	
	@staticmethod
	def detect_generated_by(source: str) -> str:
		"""Detect if content was generated by Zypherus or user-provided.
		
		Args:
			source: Source identifier from ingest_document
		
		Returns:
			"zypherus" | "user" | "system"
		"""
		source_lower = (source or "").lower()
		
		if any(x in source_lower for x in ["zypherus", "generated", "internal", "cognition"]):
			return "zypherus"
		elif any(x in source_lower for x in ["system", "config", "metadata"]):
			return "system"
		else:
			return "user"
	
	@staticmethod
	def detect_speculation(text: str) -> float:
		"""Detect speculation level and return certainty score.
		
		Returns:
			0.5-1.0 (lower = more speculative, higher = more certain)
		"""
		if not text:
			return 0.95
		
		text_lower = text.lower()
		
		# Count speculation indicators
		speculation_count = 0
		for pattern in Phase1Metadata.SPECULATION_PATTERNS:
			if re.search(pattern, text_lower):
				speculation_count += 1
		
		# Count certainty indicators
		certainty_count = 0
		for pattern in Phase1Metadata.HIGH_CERTAINTY_PATTERNS:
			if re.search(pattern, text_lower):
				certainty_count += 1
		
		# Base certainty: 0.95 (assume high by default)
		base = 0.95
		
		# Reduce for speculation (-0.10 per indicator, max -0.30)
		speculation_reduction = min(0.30, speculation_count * 0.10)
		base -= speculation_reduction
		
		# Boost for certainty (+0.02 per indicator, max +0.10)
		certainty_boost = min(0.10, certainty_count * 0.02)
		base += certainty_boost
		
		# Clamp to [0.5, 1.0]
		return max(0.5, min(1.0, base))
	
	@staticmethod
	def detect_assumption(text: str) -> bool:
		"""Detect if text contains explicit assumptions.
		
		Returns:
			True if assumption patterns detected, False otherwise
		"""
		if not text:
			return False
		
		text_lower = text.lower()
		
		for pattern in Phase1Metadata.ASSUMPTION_PATTERNS:
			if re.search(pattern, text_lower):
				return True
		
		return False
	
	@staticmethod
	def analyze_metadata(text: str, source: str) -> Tuple[str, float, bool]:
		"""Analyze all Phase 1 metadata for given text.
		
		Returns:
			(generated_by, certainty, is_assumption)
		"""
		generated_by = Phase1Metadata.detect_generated_by(source)
		certainty = Phase1Metadata.detect_speculation(text)
		is_assumption = Phase1Metadata.detect_assumption(text)
		
		return generated_by, certainty, is_assumption


__all__ = ["Phase1Metadata"]
